### ISSUE TITLE
Errors::RsyncError raised but not defined

### ISSUE THREAD

**Issue by dhovang** [myoung34/vagrant-ovirt4#110]
In file vagrant-ovirt4/action/sync_folders.rb Errors::RsyncError is raised, but the error is not defined in errors.rb, giving the following result:
vagrant-ovirt4/action/sync_folders.rb:58:in `block in call': uninitialized constant VagrantPlugins::OVirtProvider::Errors::RsyncError (NameError)

**Comment by myoung34** [comment]
Added to master branch
