### ISSUE TITLE
Listed prerequisites and install script questions

### ISSUE THREAD

**Issue by jeremytourville** [myoung34/vagrant-ovirt4#112]
I have reviewed both the list of prerequisites and the install script.  If I understand correctly the install script will take care of all the prerequisites for you, is that right?  (Assuming you are using RHEL/Centos/SCL etc.)

I also see the install script installs more components than what is listed in the prerequisite list.  ie- various devel toos such as gcc,, make, ruby, ruby-devel, etc.  How are these being used/what's the purpose?

**Comment by myoung34** [comment]
that script is more of an example of what it takes to set up ovirt on that type of box. feel free to add or remove libraries but it's more or less to show whats needed and not a golden installer

**Comment by jeremytourville** [comment]
Thanks. for clairfying
