### ISSUE TITLE
Feature request: Start vm's in normal, not in runonce mode

### ISSUE THREAD

**Issue by daFritz84** [myoung34/vagrant-ovirt4#127]
Virtual machine's are started up in a `runonce` mode. Ovirt flags such vm's with an exclamation mark which normally indicates a problem. I suggest to change the default behaviour to normal startup. If there is a valid reason for `runonce`, then make this behaviour at least adjustable.

Screenshot of vm with exclamation mark:
![image](https://user-images.githubusercontent.com/3084809/103928926-c9b5c880-511c-11eb-96b7-eb20686c08ef.png)

**Comment by myoung34** [comment]
Without a test ovirt I'm not sure I have the ability to tackle this 😱

**Comment by myoung34** [comment]
Without a test ovirt I'm not sure I have the ability to tackle this 😱

**Comment by daFritz84** [comment]
😁 Understood. 

I'm currently investigating if this can even be done considering the current behavior of ovirt. The `run-once` mode is basically set by the `cloud-init` functionality which is in turn needed to provision the ssh-key and install the qemu-guest-agent package. 

A similar issue was marked as fixed in [Ansible 22189](https://github.com/ansible/ansible/issues/22189). I still have to read up on their solution though.
