### ISSUE TITLE
'snapshot list' lists all snapshots in cluster

### ISSUE THREAD

**Issue by daFritz84** [myoung34/vagrant-ovirt4#133]
I noticed that `vagrant snapshot list` lists all snapshots of the whole cluster. I expected to see only the snapshost from the machine in the `Vagrantfile`.

I am not sure if listing "all" snapshots (i.e. from all vm's) is the correct behavior. I would rather expect to see "all" snapshots from the managed machine. See also [vmware esxi](https://github.com/josenk/vagrant-vmware-esxi/blob/e3ba1f74d08a63e513d3ad2c7a4272f24d9030de/lib/vagrant-vmware-esxi/action/snapshot_list.rb)  or [HyperV](https://github.com/hashicorp/vagrant/blob/22795b161bf67a4c0ebbe32c9ce8777cb888c4a7/plugins/providers/hyperv/driver.rb#L184) by Hashicorp themselve were there are indications that only snapshots from a particular machine are listed.

@myoung34  @GervaisdeM What is the expected behavior in your opinion? Is this considered to be a bug?

Log, only `code-for-fun-and-profit` is a snapshot from a vagrant managed vm: 
```
❯ vagrant snapshot list
==> default: Retrieving list of snapshots...
==> default:
                                  id                 description                          date
5a11b938-049c-461f-b2ae-89f26fcea050     Vor Update Talend 7.2.1     2020-11-11T09:47:36+01:00
7d6e4e29-ccc5-4147-bd07-51261e240864     code-for-fun-and-profit     2021-01-09T13:16:18+01:00
89f77717-fadf-4550-bba2-8177f536b5cb        after fatal recovery     2020-12-11T20:31:27+01:00
a5950113-9b07-4f6d-be1f-84b928791678                just-created     2020-11-30T14:16:45+01:00
28342bf2-1a6c-45c6-978a-a1e66d8a5910                just-created     2020-11-30T14:16:59+01:00
02cbd5e6-5671-4fb7-80aa-9928655627c9                 clean-start     2020-11-24T18:13:48+01:00
4a74753e-050d-41f9-8b1a-0966c6335414                 dns-routing     2020-11-26T14:59:56+01:00
```

**Comment by myoung34** [comment]
I think if you do an if condition [here](https://github.com/myoung34/vagrant-ovirt4/blob/master/lib/vagrant-ovirt4/action/snapshot_list.rb#L41) using the VM id or name as a filter (or a map reduce after grabbing all, im not picky - just less performant) this can be fixed fairly easily

**Comment by GervaisdeM** [comment]
We use vagrant with many users with multiple environments. For the snapshot feature to be useful to us, listing only snapshots for each vm would be very important.

We would run vagrant snapshot commands like:
```
vagrant snapshot save machine_name snapshot_name
vagrant snapshot list machine_name
vagrant snapshot delete machine_name snapshot_name
```

I also have concerns around name conflicts.  I can definitely see an issue where multiple users create snapshots named things like, "Clean," "saved," etc.

**Comment by myoung34** [comment]
If you filter by the machines unique id it should be fine

**Comment by daFritz84** [comment]
I still have a bit of a struggle here:

The same list feature is used as an initial filter (as a capability) for `vagrant snapshot delete`.  So regardless what I pass to snapshot delete I cannot get it to pass the initial snapshot-list filter. I tried both the `id` and the `description`, as well as the whole printed line. It seems that vagrant itself (not the plugin) does some string compare. 

@myoung34 @GervaisdeM Did anyone of you tried `vagrant snapshot delete` recently. If yes what parameters do you pass to the call, i.e. an example would be helpful.
