### ISSUE TITLE
Unable to get instance IP address with oVirt 4.3

### ISSUE THREAD

**Issue by mika-b** [myoung34/vagrant-ovirt4#136]
Trying to ssh into existing guests fails with:
```
vagrant ssh
The VM has not reported an IP address. Please ensure the ovirt-guest-agent is running and the machine is up.
```
Even after ovirt shows the address provisioning new ones is stuck at:
`==> default: Waiting for VM to get an IP address...`

Regression caused by 8772ee9fa1e3827ec6547386f2619409a170593a and b8314fb4901ec7dd47d4b9f3e61f466ca04541ae

**Comment by myoung34** [comment]
Resolved by #137
