### ISSUE TITLE
Github actions should only be executed for myoung34/vagrant-ovirt4

### ISSUE THREAD

**Issue by mika-b** [myoung34/vagrant-ovirt4#139]
I updated the master branch of my fork of the repo and github executed actions on it. Now, obviously it fails since I don't have required permissions to 'Release GEM'.

https://github.com/mika-b/vagrant-ovirt4/actions/runs/479695371

**Comment by myoung34** [comment]
Thanks for this. It's weird though because forks shouldnt be able to run actions without enabling them:

![](https://i.imgur.com/oGPF01R.png)

But ill add some logic just to triple check

**Comment by myoung34** [comment]
Oh. `scheduled workflows` 🤦 

I'll add some logic. Thanks @mika-b

**Comment by myoung34** [comment]
Fixed in theory ![](https://cdn.zappy.app/a0a9d8cde12819bb906416b0f6866d77.png)
