### ISSUE TITLE
vagrant destroy removes vm from global-status even if it fails to contact ovirt-engine and vm becomes orphaned

### ISSUE THREAD

**Issue by GervaisdeM** [myoung34/vagrant-ovirt4#144]
**Issue**
Today, I tried to destroy a vm but my local computer had lost connection to our office vpn. IMO, the results of the commands were not what they should have been.

It failed to find the vm listed in the ovirt-engine (because it couldn't talk to it), but it still removed the vm from global-status. We have a lot of environments and rely heavily on `vagrant global-status` as `vagrant status` takes forever long to run (I never have patience to wait for it to complete).

```
[gervais@vpn-dgi ~]$ vagrant global-status 
id       name            provider state  directory                           
-----------------------------------------------------------------------------
c03018c  i8manage_dev_ov ovirt4 up     /home/gervais/vagrant/ovirt         
c428b6a  i8_qa_ov        ovirt4 up     /home/gervais/vagrant/ovirt         
 
The above shows information about all known Vagrant environments
on this machine. This data is cached and may not be completely
up-to-date. To interact with any of the machines, you can go to
that directory and run Vagrant, or you can use the ID directly
with Vagrant commands from any directory. For example:
"vagrant destroy 1a2b3c4d"

[gervais@vpn-dgi ovirt] (master) $ vagrant destroy i8manage_dev_ov
==> i8manage_dev_ov: VM is not created. Please run `vagrant up` first.

[gervais@vpn-dgi ovirt] (master) $ vagrant destroy i8_qa_ov
==> i8_qa_ov: VM is not created. Please run `vagrant up` first.

[gervais@vpn-dgi ovirt] (master) $ vagrant global-status 
id       name   provider state  directory                           
--------------------------------------------------------------------
There are no active Vagrant environments on this computer! Or,
you haven't destroyed and recreated Vagrant environments that were
started with an older version of Vagrant.
```

Of course, those two vm's are still happily running in oVirt. ☹️

**Solution**
If vagrant-ovirt4 can not contact the ovirt-engine, it should fail early and not do any further tasks.

**Comparison with vsphere plugin**
```
[gervais@vpn-dgi vsphere] (master) $ vagrant destroy i8_nopuppet_vm
Failed to open TCP connection to vcenter.dgi:443 (Hostname not known: vcenter.dgi)
[gervais@vpn-dgi vsphere] (master) $ vagrant global-status 
id       name           provider state                                directory                           
----------------------------------------------------------------------------------------------------------
fecb7c4  i8_nopuppet_vm vsphere vagrant_vsphere.states.short_running /home/gervais/vagrant/vsphere       
```

**Comment by myoung34** [comment]
This is built in behavior. This plugin does not have any custom behavior for status or global-status.
Some of this is documented here: https://www.vagrantup.com/docs/cli/global-status

Specifically:

> This command does not actively verify the state of machines, and is instead based on a cache. Because of this, it is possible to see stale results (machines say they're running but they're not). For example, if you restart your computer, Vagrant would not know. To prune the invalid entries, run global status with the --prune flag.

**Comment by GervaisdeM** [comment]
@myoung34 I understand that global-status does not check and maintain an actual list of machines, but instead relies on a cache and stale machines can be pruned...

The issue is with `vagrant destroy`. If a provider can not be contacted, `vagrant destroy` should not clear the machine out of the cache that is maintained by `vagrant global-status`. You can see that the vSphere plugin checks before carrying out the `vagrant destroy` command and exits properly when it can not contact the vCentre.

IMO, this is an issue.

**Comment by myoung34** [comment]
Ah sorry @GervaisdeM I misunderstood. Ill see if I can point out some tips or maybe get in an untested PR for you to test

**Comment by GervaisdeM** [comment]
This has been resolved by Adam's PR above.
:)
