### ISSUE TITLE
Add support for multiple NICs

### ISSUE THREAD

**Issue by myoung34** [myoung34/vagrant-ovirt4#24]

**Comment by jpdugal** [comment]
I saw the ability to configure 0 or multiple network has been added already (commit 1b53415) (even though I haven't been able to get multiple networks to work). Is this particular ticket to implement a way of mapping one NIC to a specific adapter on a host?

**Comment by myoung34** [comment]
It's definitely to clean things up. those commits set the stage but you're right there's no way to specify eth0, eth1, etc or which NIC they attach to. and multiple NICs is still untested, the commits i added were to allow attaching a NIC to a VM that come up from a template with one already attached
