### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by alclonky** [myoung34/vagrant-ovirt4#32]
Hi, 
i tried installing the plugin an a CentOS VM using vagrant_1.9.1
but it failed 

Installing the '/tmp/vagrant-ovirt4.gem' plugin. This can take a few minutes...
Building native extensions.  This could take a while...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

ERROR: Failed to build gem native extension.

/opt/vagrant/embedded/bin/ruby -r ./siteconf20170109-389-c4hga3.rb extconf.rb
checking for xml2-config... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling ov_error.c
compiling ov_http_client.c
compiling ov_http_request.c
compiling ov_http_response.c
compiling ov_module.c
compiling ov_xml_reader.c
ov_xml_reader.c:24:30: fatal error: libxml/xmlreader.h: No such file or directory
 #include <libxml/xmlreader.h>
                              ^
compilation terminated.
make: *** [ov_xml_reader.o] Error 1

make failed, exit code 2

Gem files will remain installed in /root/.vagrant.d/gems/2.2.5/gems/ovirt-engine-sdk-4.0.6 for inspection.
Results logged to /root/.vagrant.d/gems/2.2.5/extensions/x86_64-linux/2.2.0/ovirt-engine-sdk-4.0.6/gem_make.out

The Header exists in vagrant installation /opt/vagrant/embedded/include/libxml2/libxml/xmlreader.h

an installation with gem works so its an vagrant issue?

gem install ovirt-engine-sdk
Fetching: ovirt-engine-sdk-4.0.6.gem (100%)
Building native extensions.  This could take a while...
Successfully installed ovirt-engine-sdk-4.0.6
Parsing documentation for ovirt-engine-sdk-4.0.6
Installing ri documentation for ovirt-engine-sdk-4.0.6
1 gem installed

**Comment by myoung34** [comment]
Don't think it's a gem issue. Try to install `yum install -y libxml2-devel` first. I'm on mobile, I think that's the package

**Comment by alclonky** [comment]
libxml2-devel is installed otherwise the installation with gem fails too

**Comment by myoung34** [comment]
I had no issues building off of master: 

```
  dev.localdomain  myoung  ~  repos  github  vagrant-ovirt4  gem list | grep -E 'ovirt|vagrant'
  dev.localdomain  myoung  ~  repos  github  vagrant-ovirt4  gem build *.gemspec
WARNING:  open-ended dependency on ovirt-engine-sdk (>= 4.0.5) is not recommended
  if ovirt-engine-sdk is semantically versioned, use:
    add_runtime_dependency 'ovirt-engine-sdk', '~> 4.0', '>= 4.0.5'
WARNING:  open-ended dependency on rspec-its (>= 0, development) is not recommended
  if rspec-its is semantically versioned, use:
    add_development_dependency 'rspec-its', '~> 0'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: vagrant-ovirt4
  Version: 0.0.1
  File: vagrant-ovirt4-0.0.1.gem
  dev.localdomain  myoung  ~  repos  github  vagrant-ovirt4  gem install vagrant-ovirt4-0.0.1.gem
Fetching: ovirt-engine-sdk-4.0.6.gem (100%)
Building native extensions.  This could take a while...
Successfully installed ovirt-engine-sdk-4.0.6
Successfully installed vagrant-ovirt4-0.0.1
Parsing documentation for ovirt-engine-sdk-4.0.6
Installing ri documentation for ovirt-engine-sdk-4.0.6
Parsing documentation for vagrant-ovirt4-0.0.1
Installing ri documentation for vagrant-ovirt4-0.0.1
Done installing documentation for ovirt-engine-sdk, vagrant-ovirt4 after 74 seconds
2 gems installed
```

the box i'm developing from is a centos 7 Vm from inside oVirt as well:

```
  dev.localdomain  myoung  ~  repos  github  vagrant-ovirt4  cat /etc/centos-release
CentOS Linux release 7.3.1611 (Core)
  dev.localdomain  myoung  ~  repos  github  vagrant-ovirt4  uname -a
Linux dev.localdomain 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by alclonky** [comment]
i **can** install the gem with "gem" thats not the Problem,
i **can't** install it with vagrant plugin install
vagrant only uses the gems installed with vagrant?

**Comment by myoung34** [comment]
oops. That might be  a misconfiguration. In the first few commits I took a lot of shortcuts so I could use vagrant with bundler. i'll look further

**Comment by myoung34** [comment]
Opened https://bugzilla.redhat.com/show_bug.cgi?id=1411594

In the mean time you can do

```
cd {vagrant-ovirt4 repo}
touch Vagrantfile
bundle install
bundle exec vagrant up
```

**Comment by myoung34** [comment]
https://github.com/mitchellh/vagrant/issues/8190
