### ISSUE TITLE
Add pre-built ovirt-guest-agent docker image to setup on atomic

### ISSUE THREAD

**Issue by myoung34** [myoung34/vagrant-ovirt4#46]
https://www.projectatomic.io/blog/2015/01/running-ovirt-guest-agent-as-privileged-container/

**Comment by jasonbrooks** [comment]
I'm doing this right now w/ `rpm-ostree install epel-release --reboot` and then `rpm-ostree install ovirt-guest-agent-common`

**Comment by myoung34** [comment]
Do you do that to a live running instance? I made this ticket mostly because I wanted to speed up instance creation time by having the actual container from the post pulled onto the box so that when I run it via cloud-init it would run near instantly and not pull all the data at that time

**Comment by jasonbrooks** [comment]
I do it while I'm building my template, so yes, it's running. Are you able to do the template-building steps on a machine that isn't live?

**Comment by myoung34** [comment]
Im not sure what you mean by isn't live, sorry.

My use-case is just pure laziness (and i'm not really familiar with atomic). When i run vagrant up i want it to be super speedy, and running vagrant up the first time on an atomic template makes it have to do a `docker pull ...` on the ovirt guest agent container, so that initial download adds time. I made this to just have most of those layers already pulled so it only has to pull the deltas and be much faster.

Admittedly I didn't know what `rpm-ostree` is (still dont) - I havent had any exposure to atomic boxes or tools that people use on them. I think ill play around a little more before i bundle in this ticket

**Comment by jasonbrooks** [comment]
The system image for an atomic host is composed from regular rpms into an ostree tree using rpm-ostree. You can add more rpms, like the ovirt agent, by running them in containers, by creating your own custom ostree image, or by using the package layering feature of rpm-ostree to layer the packages on top of the image. That third thing is what I did. I made a centos atomic VM, added the vagrant user, etc. etc. and I also layered on the ovirt-guest-agent rpm and enabled that service, before making it into a template. So when I start up a VM from that template, the agent is already there, no container to pull.

**Comment by myoung34** [comment]
@jasonbrooks awesome, thanks for that. I'm packaging up an atomic box right now so i'll see if i can get that to work!

**Comment by myoung34** [comment]
Got it working by 13a5de5f89bd9e3ee8a510fdbe218dec416380df
