### ISSUE TITLE
How do I pass the certificate of the Engine?

### ISSUE THREAD

**Issue by mykaul** [myoung34/vagrant-ovirt4#57]
If I'd like to have a secure connection, what is the configuration option for the path of the CA certificate?

**Comment by myoung34** [comment]
Didn't implement yet only how to disable it until I got it off the ground. Let me see if I can get something going on that today

**Comment by myoung34** [comment]
Does it work if the host youre running on trusts the oVirt server with insecure set to false or not set in the Bangor? It's my understanding that the flag is unfortunately named the API and that it will still be SSL, just no verification on sni. Correct if I'm wrong on the latter @mykaul

**Comment by mykaul** [comment]
Yes, it'll work with SSL without verification.
