### ISSUE TITLE
Vagrant up stucks trying to ssh to the VM

### ISSUE THREAD

**Issue by rbprado** [myoung34/vagrant-ovirt4#72]
I already used vagrant-ovirt3 and for this plugin I was used to not set the config.vm.network :private_network... and the VM gets IP by DHCP after startup.

Now I am using oVirt 4.0.5 and trying to use the vagrant-ovirt4.

I've imported a CentOS 7 Generic Cloud VM from ovirt-image-repository (openstack glance) and then did the following steps:
- Installed ovirt-guest-agent-common
- cloud-init was already installed.
- Iptables has no rules.
- Added user/pass vagrant/vagrant
- Added insecure vagrant key for vagrant user
- Added `vagrant ALL=(ALL) NOPASSWD: ALL` on `visudo`
- Added `Defaults !requiretty` on `visudo`
- Added `UseDNS no` on `/etc/ssh/sshd_config`
- Removed the nic1 by editing the VM on oVirt interface
- Created new template.

When trying to setup a VM pointing to the created template, the `vagrant up --provider=ovirt4` stucks as follow:

==> gerrit: Creating VM with the following settings...
==> gerrit:  -- Name:          gerrit-prado
==> gerrit:  -- Cluster:       node5
==> gerrit:  -- Template:      Centos7-GenericCloud
==> gerrit:  -- Console Type:  vnc
==> gerrit:  -- Memory:        
==> gerrit:  ---- Memory:      4096
==> gerrit:  ---- Guaranteed:  2048
==> gerrit:  -- Cpu:           
==> gerrit:  ---- Cores:       2
==> gerrit:  ---- Sockets:     1
==> gerrit:  ---- Threads:     1
==> gerrit:  -- Cloud-Init:    false
==> gerrit: Waiting for VM to become "ready" to start...
==> gerrit: Starting VM.
==> gerrit: Waiting for VM to get an IP address...
==> gerrit: Machine is booted and ready for use!
==> gerrit: Setting hostname...
    gerrit: 
    gerrit: Vagrant insecure key detected. Vagrant will automatically replace
    gerrit: this with a newly generated keypair for better security.
    gerrit: 
    gerrit: Inserting generated public key within guest...
    gerrit: Removing insecure key from the guest if it's present...
    gerrit: Key inserted! Disconnecting and reconnecting using new SSH key...

On the Virtual Machines Tab of oVirt is possible to see that the NIC is created and get IP from DHCP, then a second IP is set as the Vagrantfile, and finally the DHCP IP is removed, but the terminal stills as shown above.

My Vagrantfile is attached.

I would like to use just dhcp for the nic1, but if I don't set the config.vm.network (as I was used to do with vagrant-ovirt3), I get the following error:

~/.vagrant.d/gems/2.2.5/gems/vagrant-ovirt4-1.1.0/lib/vagrant-ovirt4/action/create_network_interfaces.rb:31:in `block in call': undefined method `[]' for nil:NilClass (NoMethodError)

[Vagrantfile.txt](https://github.com/myoung34/vagrant-ovirt4/files/788018/Vagrantfile.txt)

**Comment by myoung34** [comment]
This is an unforseen bug, I'll look into it. I'm currently looking into some almost-related DNS issues and can add this for after

**Comment by myoung34** [comment]
@rbprado try using the latest master commit.
Also you still need a `config.vm.network` block as you need to specify the network profile (probably `ovirtmgmt`)

I updated the README, but for DHCP:

`config.vm.network :private_network, :ovirt__network_name => 'ovirtmgmt' #DHCP`

**Comment by rbprado** [comment]
For first I've built the vagrant-ovirt4 gem on the master branch from this repo, then removed all plugins from vagrant and tryed installing again the new gem generated:

$ vagrant plugin install /home/prado/Repositories/vagrant-ovirt4/pkg/vagrant-ovirt4-1.1.0.gem
Installing the '/home/prado/Repositories/vagrant-ovirt4/pkg/vagrant-ovirt4-1.1.0.gem' plugin. This can take a few minutes...
Fetching: ovirt-engine-sdk-4.1.2.gem (100%)
Building native extensions.  This could take a while...
Fetching: filesize-0.1.1.gem (100%)
Installed the plugin 'vagrant-ovirt4 (1.1.0)'!

$ vagrant up --provider=ovirt4
Ignoring ovirt-engine-sdk-4.1.2 because its extensions are not built.  Try: gem pristine ovirt-engine-sdk --version 4.1.2
Bringing machine 'gerrit' up with 'ovirt4' provider...
==> gerrit: Creating VM with the following settings...
==> gerrit:  -- Name:          gerrit-prado
==> gerrit:  -- Cluster:       node5
==> gerrit:  -- Template:      Centos7-GenericCloud
==> gerrit:  -- Console Type:  vnc
==> gerrit:  -- Memory:        
==> gerrit:  ---- Memory:      4294 MB
==> gerrit:  ---- Maximum:     4294 MB
==> gerrit:  ---- Guaranteed:  2147 MB
==> gerrit:  -- Cpu:           
==> gerrit:  ---- Cores:       2
==> gerrit:  ---- Sockets:     1
==> gerrit:  ---- Threads:     1
==> gerrit:  -- Cloud-Init:    false
Creation failed. oVirt error message was 'For correct usage, see: https://ovirt-hml.mydomain/ovirt-engine/api/v4/model#services/vms/methods/add'

I would like to debug it but I dunno from where to begin.

**Comment by myoung34** [comment]
If you're doing it locally to test stuff you dont have to install the plugin.

```
 myoung  dev    ~  repos  github  vagrant-ovirt4  gh75  $  bundle install >/dev/null
 myoung  dev    ~  repos  github  vagrant-ovirt4  gh75  $  git fetch && git reset --hard gh75
HEAD is now at ad6361d [WIP] multiple interface handling
 myoung  dev    ~  repos  github  vagrant-ovirt4  gh75  $  bundle install >/dev/null
 myoung  dev    ~  repos  github  vagrant-ovirt4  gh75  $  which vagrant
~/.rvm/gems/ruby-2.2.3/bin/vagrant
 myoung  dev    ~  repos  github  vagrant-ovirt4  gh75  $  vagrant plugin list
You appear to be running Vagrant outside of the official installers.
Note that the installers are what ensure that Vagrant has all required
dependencies, and Vagrant assumes that these dependencies exist. By
running outside of the installer environment, Vagrant may not function
properly. To remove this warning, install Vagrant using one of the
official packages from vagrantup.com.

No plugins installed.
 myoung  dev    ~  repos  github  vagrant-ovirt4  gh75  $  bundle exec vagrant up
You appear to be running Vagrant outside of the official installers.
Note that the installers are what ensure that Vagrant has all required
dependencies, and Vagrant assumes that these dependencies exist. By
running outside of the installer environment, Vagrant may not function
properly. To remove this warning, install Vagrant using one of the
official packages from vagrantup.com.

Bringing machine 'default' up with 'ovirt4' provider...
==> default: VM is already up.
==> default: Rsyncing folder: /home/myoung/repos/github/vagrant-ovirt4/ => /vagrant
```

As long as you use `bundle install` and `which vagrant` shows that you're using the bundle installed one, it will load the plugin dynamically from cwd

You can see in my output that `vagrant plugin list` shows no plugins because it uses the one in cwd as default (meaning i dont have to specify  `--provider`

**Comment by rbprado** [comment]
Same error:

~/Repositories/vagrant-ovirt4$ bundle exec vagrant up
You appear to be running Vagrant outside of the official installers.
Note that the installers are what ensure that Vagrant has all required
dependencies, and Vagrant assumes that these dependencies exist. By
running outside of the installer environment, Vagrant may not function
properly. To remove this warning, install Vagrant using one of the
official packages from vagrantup.com.

Bringing machine 'gerrit' up with 'ovirt4' provider...
==> gerrit: Creating VM with the following settings...
==> gerrit:  -- Name:          gerrit-prado
==> gerrit:  -- Cluster:       node5
==> gerrit:  -- Template:      Centos7-GenericCloud
==> gerrit:  -- Console Type:  vnc
==> gerrit:  -- Memory:        
==> gerrit:  ---- Memory:      4294 MB
==> gerrit:  ---- Maximum:     4294 MB
==> gerrit:  ---- Guaranteed:  2147 MB
==> gerrit:  -- Cpu:           
==> gerrit:  ---- Cores:       2
==> gerrit:  ---- Sockets:     1
==> gerrit:  ---- Threads:     1
==> gerrit:  -- Cloud-Init:    false
Creation failed. oVirt error message was 'For correct usage, see: https://ovirt-hml.ped.datacom.ind.br/ovirt-engine/api/v4/model#services/vms/methods/add'

~/Repositories/vagrant-ovirt4$ which vagrant
/home/prado/.rvm/gems/ruby-2.3.1/bin/vagrant

~/Repositories/vagrant-ovirt4$ git log -1
commit 42e5fd0f8d6ee51a0dea2ca573adaa393ed40e74
Author: Marcus Young <myoung34@my.apsu.edu>
Date:   Mon Feb 20 21:55:56 2017 -0600

    Fixing gem bundle warning on filesize version dependency usage

**Comment by myoung34** [comment]
42e5fd0 is the latest commit in master, you'll need the gh75 branch to test the fix from that PR

try 

```
git fetch
git checkout gh75
git reset --hard origin gh75
```

**Comment by alclonky** [comment]
now i am getting:

==> default: Creating VM with the following settings...
INFO interface: info:  -- Name:          ovirt4test
INFO interface: info: ==> default:  -- Name:          ovirt4test
==> default:  -- Name:          ovirt4test
INFO interface: info:  -- Cluster:       Default
INFO interface: info: ==> default:  -- Cluster:       Default
==> default:  -- Cluster:       Default
INFO interface: info:  -- Template:      ubuntuvagrantx64
INFO interface: info: ==> default:  -- Template:      ubuntuvagrantx64
==> default:  -- Template:      ubuntuvagrantx64
INFO interface: info:  -- Console Type:  spice
INFO interface: info: ==> default:  -- Console Type:  spice
==> default:  -- Console Type:  spice
INFO interface: info:  -- Memory:
INFO interface: info: ==> default:  -- Memory:
==> default:  -- Memory:
INFO interface: info:  ---- Memory:      4294 MB
INFO interface: info: ==> default:  ---- Memory:      4294 MB
==> default:  ---- Memory:      4294 MB
INFO interface: info:  ---- Maximum:     4294 MB
INFO interface: info: ==> default:  ---- Maximum:     4294 MB
==> default:  ---- Maximum:     4294 MB
INFO interface: info:  ---- Guaranteed:  4294 MB
INFO interface: info: ==> default:  ---- Guaranteed:  4294 MB
==> default:  ---- Guaranteed:  4294 MB
INFO interface: info:  -- Cpu:
INFO interface: info: ==> default:  -- Cpu:
==> default:  -- Cpu:
INFO interface: info:  ---- Cores:       1
INFO interface: info: ==> default:  ---- Cores:       1
==> default:  ---- Cores:       1
INFO interface: info:  ---- Sockets:     2
INFO interface: info: ==> default:  ---- Sockets:     2
==> default:  ---- Sockets:     2
INFO interface: info:  ---- Threads:     1
INFO interface: info: ==> default:  ---- Threads:     1
==> default:  ---- Threads:     1
INFO interface: info:  -- Cloud-Init:    false
INFO interface: info: ==> default:  -- Cloud-Init:    false
==> default:  -- Cloud-Init:    false
ERROR warden: Error occurred: Creation failed. oVirt error message was 'For correct usage, see: https://cloudovirt.sq.fabasoft.com/ovirt-engine/api/v4/model#services/vms/methods/add'
INFO warden: Beginning recovery process...
INFO warden: Calling recover: #<VagrantPlugins::OVirtProvider::Action::CreateVM:0x000000034936f0>
INFO warden: Recovery complete.
INFO warden: Beginning recovery process...
INFO warden: Recovery complete.
ERROR warden: Error occurred: Creation failed. oVirt error message was 'For correct usage, see: https://cloudovirt.sq.fabasoft.com/ovirt-engine/api/v4/model#services/vms/methods/add'
INFO warden: Beginning recovery process...
INFO warden: Recovery complete.
ERROR warden: Error occurred: Creation failed. oVirt error message was 'For correct usage, see: https://cloudovirt.sq.fabasoft.com/ovirt-engine/api/v4/model#services/vms/methods/add'
INFO warden: Beginning recovery process...
INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x00000002eba828>
INFO warden: Beginning recovery process...
INFO warden: Recovery complete.
INFO warden: Recovery complete.
INFO warden: Beginning recovery process...
INFO warden: Recovery complete.
INFO warden: Beginning recovery process...
INFO warden: Recovery complete.
INFO environment: Released process lock: machine-action-51647e0d45785bcd5e834513272ea2ae
INFO environment: Running hook: environment_unload
INFO runner: Preparing hooks for middleware sequence...
INFO runner: 1 hooks defined.
INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x00000002feb328>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<VagrantPlugins::OVirtProvider::Errors::CreateVMError: Creation failed. oVirt error message was 'For correct usage, see: https://cloudovirt.sq.fabasoft.com/ovirt-engine/api/v4/model#services/vms/methods/add'>
ERROR vagrant: Creation failed. oVirt error message was 'For correct usage, see: https://cloudovirt.sq.fabasoft.com/ovirt-engine/api/v4/model#services/vms/methods/add'
ERROR vagrant: /root/.vagrant.d/gems/2.2.5/gems/vagrant-ovirt4-1.1.0/lib/vagrant-ovirt4/action/create_vm.rb:70:in `rescue in call'
/root/.vagrant.d/gems/2.2.5/gems/vagrant-ovirt4-1.1.0/lib/vagrant-ovirt4/action/create_vm.rb:66:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
/root/.vagrant.d/gems/2.2.5/gems/vagrant-ovirt4-1.1.0/lib/vagrant-ovirt4/action/set_name_of_domain.rb:17:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builtin/call.rb:53:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
/root/.vagrant.d/gems/2.2.5/gems/vagrant-ovirt4-1.1.0/lib/vagrant-ovirt4/action/connect_ovirt.rb:31:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:225:in `action_raw'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:200:in `block in action'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/environment.rb:567:in `lock'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:186:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:186:in `action'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
INFO interface: error: Creation failed. oVirt error message was 'For correct usage, see: https://cloudovirt.sq.fabasoft.com/ovirt-engine/api/v4/model#services/vms/methods/add'
Creation failed. oVirt error message was 'For correct usage, see: https://cloudovirt.sq.fabasoft.com/ovirt-engine/api/v4/model#services/vms/methods/add'
INFO interface: Machine: error-exit ["VagrantPlugins::OVirtProvider::Errors::CreateVMError", "Creation failed. oVirt error message was 'For correct usage, see: https://cloudovirt.sq.fabasoft.com/ovirt-engine/api/v4/model#services/vms/methods/add'"]

**Comment by rbprado** [comment]
It worked! Thank you for the fix and the help to test it.

**Comment by daanlevi** [comment]
I get the same error as mentioned above but it will not even create the vm 
vagrant up --provider=ovirt4
Ignoring ovirt-engine-sdk-4.1.2 because its extensions are not built.  Try: gem pristine ovirt-engine-sdk --version 4.1.2
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

cannot load such file -- ovirt-engine-sdk

What is the actual fix I need to implement?

**Comment by daanlevi** [comment]
to give some more details when I install vagrant plugin install vagrant-ovirt4 I see the file in ~/.vagrant.d/gems/2.2.5/gems/vagrant-ovirt4-1.1.0/vagrant-ovirt4.gemspec
# -*- encoding: utf-8 -*-
# stub: vagrant-ovirt4 1.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "vagrant-ovirt4"
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Marcus Young"]
  s.date = "2017-02-15"
  s.description = "Vagrant provider for oVirt and RHEV v4"
  s.email = ["myoung34@my.apsu.edu"]
  s.homepage = "https://github.com/myoung34/vagrant-ovirt4"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.5.1"
  s.summary = "This vagrant plugin provides the ability to create, control, and destroy virtual machines under oVirt/RHEV"

  s.installed_by_version = "2.4.5.1" if s.respond_to? :installed_by_version

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ovirt-engine-sdk>, [">= 4.0.6", "~> 4.0"])
    else
      s.add_dependency(%q<ovirt-engine-sdk>, [">= 4.0.6", "~> 4.0"])
    end
  else
    s.add_dependency(%q<ovirt-engine-sdk>, [">= 4.0.6", "~> 4.0"])
  end
end

But this has another content than when I clone the repository

**Comment by myoung34** [comment]
The content difference is because I haven't pushed out a new gem with these changes. I'll do that in the next few hours

**Comment by daanlevi** [comment]
Thank you for your comment myoung34
I removed the plugins and installed them again and now it seems to be working.
one remark I still get the message "Ignoring ovirt-engine-sdk-4.1.4 because its extensions are not built.  Try: gem pristine ovirt-engine-sdk --version 4.1.4"
Also when I try to get a dynamic ip it errors ".vagrant.d/gems/2.2.5/gems/vagrant-ovirt4-1.1.0/lib/vagrant-ovirt4/action/start_vm.rb:53:in `call': uninitialized constant OvirtSDK4::BootProtocol::DYNAMIC (NameError)"

In my Vagrantfile I have:
"    config.vm.network :private_network,
      :ovirt__network_name => 'ovirtmgmt' #DHCP
      # Static configuration
      #:ip => '192.168.56.100', :nictype => 'virtio', :netmask => '255.255.255.0', #normal network configuration
      #:ovirt__ip => '192.168.2.198', :ovirt__network_name => 'ovirtmgmt', :ovirt__gateway => '192.168.2.125' # oVirt specific information"
It does work when I use the static entry.

**Comment by myoung34** [comment]
That's fixed with the 1.2.0 release I'll push out when I get to the office

**Comment by myoung34** [comment]
Try the latest version, I pushed 1.2.0

**Comment by daanlevi** [comment]
Now I get the following error.
` ~/misc/develop/vagrant$ vagrant up
Ignoring ovirt-engine-sdk-4.1.4 because its extensions are not built.  Try: gem pristine ovirt-engine-sdk --version 4.1.4
Bringing machine 'default' up with 'ovirt4' provider...
==> default: Creating VM with the following settings...
==> default:  -- Name:          test-vm
==> default:  -- Cluster:       Default
==> default:  -- Template:      vm01_06-03-2017
==> default:  -- Console Type:  vnc
==> default:  -- Memory:
==> default:  ---- Memory:      256 MB
==> default:  ---- Maximum:     256 MB
==> default:  ---- Guaranteed:  256 MB
==> default:  -- Cpu:
==> default:  ---- Cores:       1
==> default:  ---- Sockets:     1
==> default:  ---- Threads:     1
==> default:  -- Cloud-Init:    false
==> default: An error occured. Recovering..
==> default: VM is not created. Please run `vagrant up` first.
/Users/levi500/.vagrant.d/gems/2.2.5/gems/ovirt-engine-sdk-4.1.4/lib/ovirtsdk4/service.rb:52:in `raise_error': Fault reason is "Request syntactically incorrect.". Fault detail is "For correct usage, see: https://dlabsr01.ds.gen.local/ovirt-engine/api/v4/model#services/vms/methods/add". HTTP response code is 400. (OvirtSDK4::Error)`
Vagrantfile
`Vagrant.configure("2") do |config|
  config.vm.box = 'ovirt4'
  config.vm.hostname = "test-vm"
  config.vm.box_url = 'https://github.com/myoung34/vagrant-ovirt4/blob/master/example_box/dummy.box?raw=true'
  config.vm.synced_folder '.', '/vagrant', disabled: true

    config.vm.network :private_network,
#      :ovirt__network_name => 'ovirtmgmt' #DHCP
      # Static configuration
      :ip => '10.68.162.71', :nictype => 'virtio', :netmask => '255.255.255.0', #normal network configuration
      :ovirt__ip => '10.68.162.71', :ovirt__network_name => 'ovirtmgmt', :ovirt__gateway => '10.68.162.1' # oVirt specific information


  config.vm.provider :ovirt4 do |ovirt|
    ovirt.url = 'https://dlabsr01.ds.gen.local/ovirt-engine/api'
    ovirt.username = "admin@internal"
    ovirt.password = "bPfCivIpZY3YK5q9hWkY"
    ovirt.insecure = true
    ovirt.debug = true
    ovirt.cluster = 'Default'
#    ovirt.template = 'vagrant-centos7'
    ovirt.template = 'vm01_06-03-2017'
    ovirt.console = 'vnc'
#    ovirt.memory_size = '1 GiB' #see https://github.com/dominikh/filesize for usage
#    ovirt.memory_guaranteed = '256 MB' #see https://github.com/dominikh/filesize for usage
#    ovirt.cpu_cores = 2
#    ovirt.cpu_sockets = 2
#    ovirt.cpu_threads = 2
#    ovirt.cloud_init =<<EOF
#write_files:
#  - content: |
#      Hello, world!
#    path: /tmp/greeting.txt
#    permissions: '0644'
#EOF
  end
end`

I am trying all kinds of different options but how can I enable more logging?

**Comment by myoung34** [comment]
`ovirt.debug = true` is what provides the full stack trace on an error
What version is your ovirt server?

**Comment by myoung34** [comment]
@daanlevi can you try to run against version 1.2.1? I reverted the underlying ruby sdk to 4.0.x instead of 4.1.x to see if it helps.

```
git pull
git checkout release/1.2.1
bundle install # you should see that it installed vagrant-ovirt4 -v 1.2.1 and ovirt-engine-sdk 4.0.12
# put your Vagrantfile here
bundle exec vagrant up #please ensure that the versions are 1.2.1 and 4.0.12
```

**Comment by daanlevi** [comment]
We are using Version 4.0.5.5-1.el7.centos
I already had debug = true and that was the output that I pasted.
I tried to build the version with bundle on my mac but then I got an error.
```
Bundler could not find compatible versions for gem "ruby":
  In Gemfile:
    ruby

    vagrant was resolved to 1.9.3.dev, which depends on
      ruby (~> 2.2)
```
Strange since i have ruby 2.4 installed with brew and rebooted my mac.

So when I comment out the vagrant part in the Gemfile I see the other parts getting build.
Then when I execute bundle exec vagrant up I get
```
bundler: failed to load command: vagrant (/usr/local/bin/vagrant)
Gem::LoadError: vagrant is not part of the bundle. Add it to Gemfile.
  /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.6/lib/bundler/rubygems_integration.rb:351:in `block (2 levels) in replace_gem'
  /usr/local/bin/vagrant:22:in `<top (required)>'
```
Is there another way I can include the vagrant to the build?
Or to use to use ovirt-engine-sdk 4.0.12 on the official 1.2.0 release?

**Comment by myoung34** [comment]
On the official? no, vagrant bundles their stuff with it so there's no way to mix and match even manually. You can try to build it and test it via vagrant, i published [these yesterday to assist in doing this in Jenkins](https://hub.docker.com/r/myoung34/vagrant/tags/)

See the usage, but that includes ruby 2.2.6 and vagrant

**Comment by myoung34** [comment]
@daanlevi can you open a new ticket to see if we can move this somewhere else?

**Comment by rbprado** [comment]
The error **Fault reason is "Request syntactically incorrect."** is also happening here with 1.1.0 and 1.2.0.

The version 1.2.1 is working fine here.

**Comment by myoung34** [comment]
@rbprado alright, let me run some tests using `1.2.1` against my server (which is 4.1)
If it works I'll push that out since it means that it adds more support all-around

**Comment by myoung34** [comment]
@rbprado @daanlevi i released 1.2.1 which sets the ovirt gem to the latest 4.0 and seems to resolve both of your issues

**Comment by rbprado** [comment]
I was testing it with DHCP right now and it looks not to be setting up the eth0 on the VM.

```
==> template: Creating VM with the following settings...
==> template:  -- Name:          builder-pd3700-1.ped.datacom.ind.br
==> template:  -- Cluster:       node5
==> template:  -- Template:      template-vagrant-ubuntu1604
==> template:  -- Console Type:  vnc
==> template:  -- Memory:        
==> template:  ---- Memory:      4294 MB
==> template:  ---- Maximum:     4294 MB
==> template:  ---- Guaranteed:  2147 MB
==> template:  -- Cpu:           
==> template:  ---- Cores:       2
==> template:  ---- Sockets:     2
==> template:  ---- Threads:     2
==> template:  -- Cloud-Init:    false
==> template: Waiting for VM to become "ready" to start...
==> template: Starting VM.
==> template: Waiting for VM to get an IP address...
```

At this point I have to enter on a VM tty and run `dhclient`, then the eth0 is set up and got IP. Otherwise vagrant tries to halt the VM:

```
==> template: Waiting for VM to become "ready" to start...
==> template: Starting VM.
==> template: Waiting for VM to get an IP address...
==> template: Halting VM...
==> template: Waiting for VM to shutdown...
==> template: Removing VM...
==> template: An error occured. Recovering..
==> template: VM is not created. Please run `vagrant up` first.
/home/prado/.vagrant.d/gems/2.2.5/gems/vagrant-ovirt4-1.2.1/lib/vagrant-ovirt4/action/wait_till_up.rb:52:in `call': uninitialized constant VagrantPlugins::OVirtProvider::Action::WaitTillUp::NoIPError (NameError)
```

**Comment by myoung34** [comment]
what does line 52 look like on that file? I'm not getting a const issue locally

I did find an issue with an unrelated `raise` but not that one.

`The VM has not reported an IP address. Please ensure the ovirt-guest-agent is running and the machine is up.`

**Comment by myoung34** [comment]
@rbprado I fixed it. When I version bumped to `1.2.1` I didn't bump it in the Gemfile.lock, so you're still using `1.2.0` as an include from bundler. I fixed it correctly along with some unrelated exception calls in `1.2.2`

**Comment by rbprado** [comment]
It's yet getting stucked with 1.2.2:
´´´
...
==> template: Waiting for VM to get an IP address...
The VM has not reported an IP address. Please ensure the ovirt-guest-agent is running and the machine is up.
´´´
I checked it out and the ovirt-guest-agent is running.
Running the `dhclient` while waiting the IP, solves the problem.

**Comment by myoung34** [comment]
This isn't an issue with vagrant, the VM has to successfully  report it's IP to the oVirt server. The vagrant provider tries to give it an amount of time to do so via polling. If you have to run anything to get it to work you can use user data to try to automate dhclient or whatever you need

**Comment by rbprado** [comment]
Sorry!
My template /etc/network/interfaces was set with iface eth0 inet static, now its dhcp :)

Thank you for the help.
