### ISSUE TITLE
up failes if template has network configured

### ISSUE THREAD

**Issue by alclonky** [myoung34/vagrant-ovirt4#75]
my templates have network preconfigured, 
if i don't set network in Vagrantfile i get:
INFO warden: Calling IN action: #<VagrantPlugins::OVirtProvider::Action::CreateNetworkInterfaces:0x00000003a53dd8>
ERROR warden: Error occurred: undefined method `[]' for nil:NilClass

if i set network in Vagrantfile i get:
Error while adding new interface to VM. Fault reason is "Operation Failed". Fault detail is "[Network interface is already in use.]". HTTP response code is 409.

**Comment by myoung34** [comment]
can you post the whole stack trace from both? it'll help track it down

**Comment by alclonky** [comment]
[with_network.txt](https://github.com/myoung34/vagrant-ovirt4/files/790621/with_network.txt)
[without_network.txt](https://github.com/myoung34/vagrant-ovirt4/files/790622/without_network.txt)

**Comment by myoung34** [comment]
@alclonky can you try #76 ?

**Comment by alclonky** [comment]
no i am getting:

==> default: Creating VM with the following settings...
INFO interface: info:  -- Name:          ovirt4test
INFO interface: info: ==> default:  -- Name:          ovirt4test
==> default:  -- Name:          ovirt4test
INFO interface: info:  -- Cluster:       Default
INFO interface: info: ==> default:  -- Cluster:       Default
==> default:  -- Cluster:       Default
INFO interface: info:  -- Template:      ubuntuvagrantx64
INFO interface: info: ==> default:  -- Template:      ubuntuvagrantx64
==> default:  -- Template:      ubuntuvagrantx64
INFO interface: info:  -- Console Type:  spice
INFO interface: info: ==> default:  -- Console Type:  spice
==> default:  -- Console Type:  spice
INFO interface: info:  -- Memory:
INFO interface: info: ==> default:  -- Memory:
==> default:  -- Memory:
INFO interface: info:  ---- Memory:      4294 MB
INFO interface: info: ==> default:  ---- Memory:      4294 MB
==> default:  ---- Memory:      4294 MB
INFO interface: info:  ---- Maximum:     4294 MB
INFO interface: info: ==> default:  ---- Maximum:     4294 MB
==> default:  ---- Maximum:     4294 MB
INFO interface: info:  ---- Guaranteed:  4294 MB
INFO interface: info: ==> default:  ---- Guaranteed:  4294 MB
==> default:  ---- Guaranteed:  4294 MB
INFO interface: info:  -- Cpu:
INFO interface: info: ==> default:  -- Cpu:
==> default:  -- Cpu:
INFO interface: info:  ---- Cores:       1
INFO interface: info: ==> default:  ---- Cores:       1
==> default:  ---- Cores:       1
INFO interface: info:  ---- Sockets:     2
INFO interface: info: ==> default:  ---- Sockets:     2
==> default:  ---- Sockets:     2
INFO interface: info:  ---- Threads:     1
INFO interface: info: ==> default:  ---- Threads:     1
==> default:  ---- Threads:     1
INFO interface: info:  -- Cloud-Init:    false
INFO interface: info: ==> default:  -- Cloud-Init:    false
==> default:  -- Cloud-Init:    false
ERROR warden: Error occurred: Creation failed. oVirt error message was 'For correct usage, see: https://cloudovirt.sq.fabasoft.com/ovirt-engine/api/v4/model#services/vms/methods/add'
INFO warden: Beginning recovery process...
INFO warden: Calling recover: #<VagrantPlugins::OVirtProvider::Action::CreateVM:0x000000034936f0>
INFO warden: Recovery complete.
INFO warden: Beginning recovery process...
INFO warden: Recovery complete.
ERROR warden: Error occurred: Creation failed. oVirt error message was 'For correct usage, see: https://cloudovirt.sq.fabasoft.com/ovirt-engine/api/v4/model#services/vms/methods/add'
INFO warden: Beginning recovery process...
INFO warden: Recovery complete.
ERROR warden: Error occurred: Creation failed. oVirt error message was 'For correct usage, see: https://cloudovirt.sq.fabasoft.com/ovirt-engine/api/v4/model#services/vms/methods/add'
INFO warden: Beginning recovery process...
INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x00000002eba828>
INFO warden: Beginning recovery process...
INFO warden: Recovery complete.
INFO warden: Recovery complete.
INFO warden: Beginning recovery process...
INFO warden: Recovery complete.
INFO warden: Beginning recovery process...
INFO warden: Recovery complete.
INFO environment: Released process lock: machine-action-51647e0d45785bcd5e834513272ea2ae
INFO environment: Running hook: environment_unload
INFO runner: Preparing hooks for middleware sequence...
INFO runner: 1 hooks defined.
INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x00000002feb328>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<VagrantPlugins::OVirtProvider::Errors::CreateVMError: Creation failed. oVirt error message was 'For correct usage, see: https://cloudovirt.sq.fabasoft.com/ovirt-engine/api/v4/model#services/vms/methods/add'>
ERROR vagrant: Creation failed. oVirt error message was 'For correct usage, see: https://cloudovirt.sq.fabasoft.com/ovirt-engine/api/v4/model#services/vms/methods/add'
ERROR vagrant: /root/.vagrant.d/gems/2.2.5/gems/vagrant-ovirt4-1.1.0/lib/vagrant-ovirt4/action/create_vm.rb:70:in `rescue in call'
/root/.vagrant.d/gems/2.2.5/gems/vagrant-ovirt4-1.1.0/lib/vagrant-ovirt4/action/create_vm.rb:66:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
/root/.vagrant.d/gems/2.2.5/gems/vagrant-ovirt4-1.1.0/lib/vagrant-ovirt4/action/set_name_of_domain.rb:17:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builtin/call.rb:53:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
/root/.vagrant.d/gems/2.2.5/gems/vagrant-ovirt4-1.1.0/lib/vagrant-ovirt4/action/connect_ovirt.rb:31:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:225:in `action_raw'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:200:in `block in action'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/environment.rb:567:in `lock'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:186:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:186:in `action'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
INFO interface: error: Creation failed. oVirt error message was 'For correct usage, see: https://cloudovirt.sq.fabasoft.com/ovirt-engine/api/v4/model#services/vms/methods/add'
Creation failed. oVirt error message was 'For correct usage, see: https://cloudovirt.sq.fabasoft.com/ovirt-engine/api/v4/model#services/vms/methods/add'
INFO interface: Machine: error-exit ["VagrantPlugins::OVirtProvider::Errors::CreateVMError", "Creation failed. oVirt error message was 'For correct usage, see: https://cloudovirt.sq.fabasoft.com/ovirt-engine/api/v4/model#services/vms/methods/add'"]

**Comment by myoung34** [comment]
@alclonky try again but make sure you have `ovirt.debug = true`, i added a commit to not swallow the upstream error if that flag is set

```
git fetch
git co gh75
git reset --hard origin/gh75
```

**Comment by alclonky** [comment]
/root/.vagrant.d/gems/2.2.5/gems/ovirt-engine-sdk-4.1.2/lib/ovirtsdk4/service.rb:52:in `raise_error': Fault reason is "Request syntactically incorrect.". Fault detail is "For correct usage, see: https://cloudovirt.sq.fabasoft.com/ovirt-engine/api/v4/model#services/vms/methods/add". HTTP response code is 400. (OvirtSDK4::Error)
        from /root/.vagrant.d/gems/2.2.5/gems/ovirt-engine-sdk-4.1.2/lib/ovirtsdk4/service.rb:67:in `check_fault'
        from /root/.vagrant.d/gems/2.2.5/gems/ovirt-engine-sdk-4.1.2/lib/ovirtsdk4/services.rb:33600:in `add'
        from /root/.vagrant.d/gems/2.2.5/gems/vagrant-ovirt4-1.1.0/lib/vagrant-ovirt4/action/create_vm.rb:67:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
        from /root/.vagrant.d/gems/2.2.5/gems/vagrant-ovirt4-1.1.0/lib/vagrant-ovirt4/action/set_name_of_domain.rb:17:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builtin/call.rb:53:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
        from /root/.vagrant.d/gems/2.2.5/gems/vagrant-ovirt4-1.1.0/lib/vagrant-ovirt4/action/connect_ovirt.rb:31:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:225:in `action_raw'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:200:in `block in action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/environment.rb:567:in `lock'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:186:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:186:in `action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'

**Comment by myoung34** [comment]
what version are you running of oVirt ?

**Comment by alclonky** [comment]
4.0.3
waiting on some bugs to be fixed until i can update to 4.1

**Comment by myoung34** [comment]
My guess is that this isn't compatible with 4.0.3

https://www.ovirt.org/release/4.1.0/ shows  a lot of changes to the REST API
Also I have the gem set to `ovirt-engine-sdk-4.1.2`

**Comment by alclonky** [comment]
no problem for me if <4.1 isn't going to be supported,
but can't help testing until i can update

**Comment by myoung34** [comment]
You can try to set the version of the ruby sdk to 4.0.3 in the `vagrant-ovirt4.gemspec` and trying again with `bundle install` to see if that helps

**Comment by myoung34** [comment]
Until I hit a 1:1 matching point with the oVirt compatibility the base sdk gem is liable to change but I'm likely not going to change it past 4.1 since all commands are currently working

**Comment by alclonky** [comment]
using 4.0.3, it works now (with and without creating network)

**Comment by alclonky** [comment]
sorry was too late yesterday, the not configure network and use the interface from template case has still an issue

/root/.vagrant.d/gems/2.2.5/gems/vagrant-ovirt4-1.1.0/lib/vagrant-ovirt4/action/start_vm.rb:42:in `call': undefined method `[]' for nil:NilClass (NoMethodError)
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builtin/set_hostname.rb:16:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
        from /root/.vagrant.d/gems/2.2.5/gems/vagrant-ovirt4-1.1.0/lib/vagrant-ovirt4/action/create_network_interfaces.rb:76:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builtin/provision.rb:80:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
        from /root/.vagrant.d/gems/2.2.5/gems/vagrant-ovirt4-1.1.0/lib/vagrant-ovirt4/action/create_vm.rb:103:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
        from /root/.vagrant.d/gems/2.2.5/gems/vagrant-ovirt4-1.1.0/lib/vagrant-ovirt4/action/set_name_of_domain.rb:17:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builtin/call.rb:53:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
        from /root/.vagrant.d/gems/2.2.5/gems/vagrant-ovirt4-1.1.0/lib/vagrant-ovirt4/action/connect_ovirt.rb:31:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:225:in `action_raw'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:200:in `block in action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/environment.rb:567:in `lock'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:186:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:186:in `action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'

**Comment by myoung34** [comment]
@alclonky can you try the hash in #78?

```
git checkout origin/gh75_again
git fetch
git reset --hard origin/gh75_again
```

**Comment by alclonky** [comment]
```
IINFO interface: info: ==> default: Creating VM with the following settings...
==> default: Creating VM with the following settings...
 INFO interface: info:  -- Name:          vagrant
 INFO interface: info: ==> default:  -- Name:          vagrant
==> default:  -- Name:          vagrant
 INFO interface: info:  -- Cluster:       Default
 INFO interface: info: ==> default:  -- Cluster:       Default
==> default:  -- Cluster:       Default
 INFO interface: info:  -- Template:      linuxtemplatev7
 INFO interface: info: ==> default:  -- Template:      linuxtemplatev7
==> default:  -- Template:      linuxtemplatev7
 INFO interface: info:  -- Console Type:  spice
 INFO interface: info: ==> default:  -- Console Type:  spice
==> default:  -- Console Type:  spice
 INFO interface: info:  -- Memory:
 INFO interface: info: ==> default:  -- Memory:
==> default:  -- Memory:
 INFO interface: info:  ---- Memory:      21474 MB
 INFO interface: info: ==> default:  ---- Memory:      21474 MB
==> default:  ---- Memory:      21474 MB
 INFO interface: info:  ---- Maximum:     21474 MB
 INFO interface: info: ==> default:  ---- Maximum:     21474 MB
==> default:  ---- Maximum:     21474 MB
 INFO interface: info:  ---- Guaranteed:  10737 MB
 INFO interface: info: ==> default:  ---- Guaranteed:  10737 MB
==> default:  ---- Guaranteed:  10737 MB
 INFO interface: info:  -- Cpu:
 INFO interface: info: ==> default:  -- Cpu:
==> default:  -- Cpu:
 INFO interface: info:  ---- Cores:       8
 INFO interface: info: ==> default:  ---- Cores:       8
==> default:  ---- Cores:       8
 INFO interface: info:  ---- Sockets:     1
 INFO interface: info: ==> default:  ---- Sockets:     1
==> default:  ---- Sockets:     1
 INFO interface: info:  ---- Threads:     1
 INFO interface: info: ==> default:  ---- Threads:     1
==> default:  ---- Threads:     1
 INFO interface: info:  -- Cloud-Init:    false
 INFO interface: info: ==> default:  -- Cloud-Init:    false
==> default:  -- Cloud-Init:    false
 INFO machine: New machine ID: "390bad66-8a65-409b-87f9-3b87fe6e3240"
 INFO interface: info: Waiting for VM to become "ready" to start...
 INFO interface: info: ==> default: Waiting for VM to become "ready" to start...
==> default: Waiting for VM to become "ready" to start...
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::Provision:0x000000032609f0>
 INFO provision: Checking provisioner sentinel file...
 INFO interface: info: Auto-generating node name for Chef...
 INFO interface: info: ==> default: Auto-generating node name for Chef...
==> default: Auto-generating node name for Chef...
 INFO chef: Loading cached node_name...
 INFO warden: Calling IN action: #<VagrantPlugins::OVirtProvider::Action::CreateNetworkInterfaces:0x0000000323e800>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::SetHostname:0x0000000321cc50>
 INFO warden: Calling IN action: #<VagrantPlugins::OVirtProvider::Action::StartVM:0x0000000321cc28>
 INFO interface: info: Starting VM.
 INFO interface: info: ==> default: Starting VM.
==> default: Starting VM.
ERROR warden: Error occurred: undefined method `empty?' for nil:NilClass
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<VagrantPlugins::OVirtProvider::Action::CreateVM:0x000000032a48a8>
 INFO interface: info: An error occured. Recovering..
 INFO interface: info: ==> default: An error occured. Recovering..
==> default: An error occured. Recovering..

```

**Comment by myoung34** [comment]
alright sorry for being the beta user @alclonky can you try again? same 3 git commands

**Comment by myoung34** [comment]
can you add `ovirt.debug = true` to your vagrant file? i'd like to see the whole stack

**Comment by alclonky** [comment]
[debug.txt](https://github.com/myoung34/vagrant-ovirt4/files/794052/debug.txt)

**Comment by myoung34** [comment]
I removed some optimizations and pushed them back up to that branch

**Comment by alclonky** [comment]
works now

**Comment by myoung34** [comment]
Thanks for your patience =)
