### ISSUE TITLE
Remote boxes aren't downloaded

### ISSUE THREAD

**Issue by alclonky** [myoung34/vagrant-ovirt4#77]
if i create a Vagrantfile:

Vagrant.configure("2") do |config|
  config.vm.provider "ovirt4"
  config.vm.box = "cloudbackend7"
  config.vm.box_download_ca_cert = "/data/ca-bundle.pem"
  config.vm.box_download_location_trusted = true
  config.vm.box_url = 'https://artifactory.mycom.com:443/artifactory/api/vagrant/sq-vagrant/cloudbackend7'
end

the box isn't downloaded and so there are no settings

vagrant up --no-provision
Bringing machine 'default' up with 'ovirt4' provider...
==> default: Creating VM with the following settings...
==> default:  -- Name:          vagrant
==> default:  -- Cluster:
==> default:  -- Template:
==> default:  -- Console Type:
==> default:  -- Memory:
==> default:  ---- Memory:      256
==> default:  ---- Guaranteed:  256
==> default:  -- Cpu:
==> default:  ---- Cores:       1
==> default:  ---- Sockets:     1
==> default:  ---- Threads:     1
==> default:  -- Cloud-Init:    false
Creation failed. oVirt error message was 'Can't send request: URL using bad/illegal format or missing URL'

If i do the same with vsphere it works

Vagrant.configure("2") do |config|
  config.vm.provider "vsphere"
  config.vm.box = "macclient"
  config.vm.box_download_ca_cert = "/data/ca-bundle.pem"
  config.vm.box_download_location_trusted = true
  config.vm.box_url = 'https://artifactory.mycom.com:443/artifactory/api/vagrant/sq-vagrant/macclient'
end

vagrant up --no-provision
==> default: Box 'macclient' could not be found. Attempting to find and install...
    default: Box Provider: vsphere
    default: Box Version: >= 0
==> default: Loading metadata for box 'https://artifactory.mycom.com:443/artifactory/api/vagrant/sq-vagrant/macclient'
    default: URL: https://artifactory.mycom.com:443/artifactory/api/vagrant/sq-vagrant/macclient
==> default: Adding box 'macclient' (v1) for provider: vsphere
    default: Downloading: https://artifactory.mycom.com:443/artifactory/api/vagrant/sq-vagrant/macclient.box
==> default: Successfully added box 'macclient' (v1) for 'vsphere'!
Bringing machine 'default' up with 'vsphere' provider...

if I add the box with box add first it works for ovirt too, but thats not what i want

**Comment by myoung34** [comment]
If it works with the url pointed at github there's not much I can help you with.
It's either: permissions, not found, or not valid/corrupt.

I'm not familiar with hosting vagrant boxes on artifactory. My question is: is it worth the effort?  If you look at [here](example_box/README.md) you'll see that it's basically just an empty tarball. Since you already depend on rubygems.org and probably github i'm not sure I'd be the one to tell you it's worth hosting that 437 byte file anywhere else that adds complexity.

**Comment by alclonky** [comment]
if i box add the same url it works so i don't think its permissions, not found, or not valid/corrupt.

and yes it is usefull to host the boxes. I need to know which Box Version is used by which build.

I think you have to trigger "HandleBox"? like in [vsphere](https://github.com/nsidc/vagrant-vsphere/blob/9b3b2781b6e748f9f78b84245903a88c63b63350/lib/vSphere/action.rb)

```
def self.action_up
  Vagrant::Action::Builder.new.tap do |b|
     b.use HandleBox
     b.use ConfigValidate
     b.use ConnectVSphere
```
vs.
```
def self.action_up
  Vagrant::Action::Builder.new.tap do |b|
    b.use ConfigValidate
    b.use ConnectOVirt
```
debug output vsphere:

```
INFO box_collection: Box not found: macclient (vsphere)
 INFO machine: Initializing machine: default
 INFO machine:   - Provider: VagrantPlugins::VSphere::Provider
 INFO machine:   - Box:
 INFO machine:   - Data dir: /test2/.vagrant/machines/default/vsphere
 INFO machine: Calling action: get_state on provider vSphere (new)
 INFO interface: Machine: action ["get_state", "start", {:target=>:default}]
 INFO host: Autodetecting host type for [#<Vagrant::Environment: /test2>]
DEBUG host: Trying: arch
DEBUG host: Trying: darwin
DEBUG host: Trying: freebsd
DEBUG host: Trying: gentoo
DEBUG host: Trying: redhat
 INFO host: Detected: redhat!
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 2 hooks defined.
 INFO runner: Running action: machine_action_get_state #<Vagrant::Action::Builder:0x000000016ef068>
 INFO warden: Calling IN action: #<VagrantPlugins::Triggers::Action::Trigger:0x00000003e45d38>
 INFO warden: Calling IN action: #<VagrantPlugins::Triggers::Action::Trigger:0x00000003e59dd8>
DEBUG trigger: Looking for triggers with:
DEBUG trigger: -- action: get_state
DEBUG trigger: -- condition: instead_of
DEBUG trigger: -- vm: default
 INFO warden: Calling IN action: #<VagrantPlugins::Triggers::Action::Trigger:0x00000003e6ea80>
DEBUG trigger: Looking for triggers with:
DEBUG trigger: -- action: get_state
DEBUG trigger: -- condition: before
DEBUG trigger: -- vm: default
 **INFO warden: Calling IN action: #<Vagrant::Action::Builtin::HandleBox:0x00000003e832a0>
 INFO interface: output: Box 'macclient' could not be found. Attempting to find and install...
 INFO interface: output: ==> default: Box 'macclient' could not be found. Attempting to find and install..**.
```


debug output ovirt:

```
INFO box_collection: Box not found: appliancebackend7 (ovirt4)
 INFO machine: Initializing machine: default
 INFO machine:   - Provider: VagrantPlugins::OVirtProvider::Provider
 INFO machine:   - Box:
 INFO machine:   - Data dir: /test/.vagrant/machines/default/ovirt4
 INFO machine: Calling action: read_state on provider oVirt (new)
DEBUG environment: Attempting to acquire process-lock: machine-action-50e8991d5120d70d47dbd72716c8d486
DEBUG environment: Attempting to acquire process-lock: dotlock
 INFO environment: Acquired process lock: dotlock
 INFO environment: Released process lock: dotlock
 INFO environment: Acquired process lock: machine-action-50e8991d5120d70d47dbd72716c8d486
 INFO interface: Machine: action ["read_state", "start", {:target=>:default}]
 INFO host: Autodetecting host type for [#<Vagrant::Environment: /test>]
DEBUG host: Trying: arch
DEBUG host: Trying: darwin
DEBUG host: Trying: freebsd
DEBUG host: Trying: gentoo
DEBUG host: Trying: redhat
 INFO host: Detected: redhat!
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 2 hooks defined.
 INFO runner: Running action: machine_action_read_state #<Vagrant::Action::Builder:0x0000000444ecc0>
 INFO warden: Calling IN action: #<VagrantPlugins::Triggers::Action::Trigger:0x000000043d4fd8>
 INFO warden: Calling IN action: #<VagrantPlugins::Triggers::Action::Trigger:0x000000043b4210>
DEBUG trigger: Looking for triggers with:
DEBUG trigger: -- action: read_state
DEBUG trigger: -- condition: instead_of
DEBUG trigger: -- vm: default
 INFO warden: Calling IN action: #<VagrantPlugins::Triggers::Action::Trigger:0x0000000439b738>
DEBUG trigger: Looking for triggers with:
DEBUG trigger: -- action: read_state
DEBUG trigger: -- condition: before
DEBUG trigger: -- vm: default
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::ConfigValidate:0x000000043826e8>
 INFO warden: Calling IN action: #<VagrantPlugins::OVirtProvider::Action::ConnectOVirt:0x000000043826c0>
 INFO connect_ovirt: Connecting to oVirt () ...
 INFO warden: Calling IN action: #<VagrantPlugins::OVirtProvider::Action::ReadState:0x0000000436d860>
 INFO warden: Calling OUT action: #<VagrantPlugins::OVirtProvider::Action::ReadState:0x0000000436d860>
 INFO warden: Calling OUT action: #<VagrantPlugins::OVirtProvider::Action::ConnectOVirt:0x000000043826c0>
 INFO warden: Calling OUT action: #<Vagrant::Action::Builtin::ConfigValidate:0x000000043826e8>
 INFO warden: Calling OUT action: #<VagrantPlugins::Triggers::Action::Trigger:0x0000000439b738>
 INFO warden: Calling OUT action: #<VagrantPlugins::Triggers::Action::Trigger:0x000000043b4210>
DEBUG trigger: Looking for triggers with:
DEBUG trigger: -- action: read_state
DEBUG trigger: -- condition: after
DEBUG trigger: -- vm: default
 INFO warden: Calling OUT action: #<VagrantPlugins::Triggers::Action::Trigger:0x000000043d4fd8>
 INFO interface: Machine: action ["read_state", "end", {:target=>:default}]
 INFO environment: Released process lock: machine-action-50e8991d5120d70d47dbd72716c8d486
DEBUG environment: Attempting to acquire process-lock: dotlock
 INFO environment: Acquired process lock: dotlock
 INFO environment: Released process lock: dotlock
 INFO machine: New machine ID: nil
 INFO interface: Machine: metadata ["provider", :ovirt4, {:target=>:default}]

```

**Comment by myoung34** [comment]
If you want to try that and issue a PR I'd accept it. If i make that change I'll have to go back and forth with you to test it since I'm not having any related issues

**Comment by myoung34** [comment]
Going to close this until I can replicate it on my side
