### ISSUE TITLE
vagrant-ovirt4 1.2 compatibility issues

### ISSUE THREAD

**Issue by daanlevi** [myoung34/vagrant-ovirt4#80]
As discussed in an earlier thread the 1.2 version of vagrant-ovirt4-1.2 seems to throw some errors when running against ovirt Version 4.0.5.5-1.el7.centos and using ovirt-engine-sdk-4.1.4

**Comment by myoung34** [comment]
I changed the requirement to `4.0.12` to see if it helps, it's in the `release/1.2.1` branch.

i created a docker image in the last few days to help with CI and it will help you the same way:
https://hub.docker.com/r/myoung34/vagrant/


```
git fetch
git checkout origin/release/1.2.1
# make sure your Vagrantfile exists here to make it easier
docker run   -it  -v $(pwd):/opt/vagrant-plugin   myoung34/vagrant:1.9.1   /bin/bash 
```

once you're inside the container:

```
cd /opt/vagrant-plugin
bundle install
bundle exec vagrant up
bundle exec destroy -f #etc
```

**Comment by daanlevi** [comment]
I had to Use json 1.8.2 since the 1.7.7 version was not working with ruby 2.2.
After that I was able to connect to our ovirt cluster and create a vm.

**Comment by myoung34** [comment]
glad it got worked out.
