### ISSUE TITLE
Support for sub-templates?

### ISSUE THREAD

**Issue by jasonbrooks** [myoung34/vagrant-ovirt4#81]
Does the plugin support sub-templates? I created vagrant templates as sub versions of regular templates, but I couldn't tell how to reference them in my vagrantfile.

**Comment by myoung34** [comment]
`¯\_(ツ)_/¯ `

I actually have no idea, my Vagrantfiles have been fairly simple in comparison (i usually just spin up container hosts). I'm not familiar with subtemplates aside from kitchen vagrant templates

**Comment by cliffe** [comment]
This would be a useful feature. We have some instances where oVirt is not selecting the most recent revision of a template. It would have helped us with a solution if we could specify which revision of template to use.

**Comment by myoung34** [comment]
Im OK to merge a PR for this, but its a few years old 
If someone can help submit a scaffold for this Im happy to submit feedback and potentially merge it
