### ISSUE TITLE
Allow not setting Hostname 

### ISSUE THREAD

**Issue by alclonky** [myoung34/vagrant-ovirt4#91]
with your ovirt3 plugin I was able to only set the name for the vm in ovirt but not the hostname inside the vm.
now its the same configuration.
For Windows Boxes that means a reboot after creating the VM which costs lot of time.

**Comment by myoung34** [comment]
That behavior is likely a bug in oVirt 3, but that behavior in the new one can [be found here](https://github.com/myoung34/vagrant-ovirt4/blob/master/lib/vagrant-ovirt4/action/start_vm.rb#L62)

I'm not sure it makes sense to _not_ set the hostname, that's rpetty standard across vagrant providers.
If you submitted a PR for a new configuration flag `set_hostname => false` i wouldn't be against it

**Comment by myoung34** [comment]
Im OK to merge a PR for this, but its a few years old 
If someone can help submit a scaffold for this Im happy to submit feedback and potentially merge it
