### ISSUE TITLE
Configure mac address

### ISSUE THREAD

**Issue by rgajendran** [myoung34/vagrant-ovirt4#92]
Is there a way to configure mac address when spinning up vagrant into ovirt?
```
config.vm.network :private_network,
    :ovirt__network_name => 'ovirtmgmt' #DHCP
```
Tried to configure with `mac => "5CA1AB1E0001"` & `base_mac`. Its not working. Any idea?

**Comment by myoung34** [comment]
The way to do this would be `config.vm.network :bridged , :mac => "080027XXXXXX"` but it's not currently supported. Ill keep this ticket here as a feature request

**Comment by myoung34** [comment]
Im OK to merge a PR for this, but its a few years old 
If someone can help submit a scaffold for this Im happy to submit feedback and potentially merge it
