### ISSUE TITLE
allow multiple private_network creation

### ISSUE THREAD

**Issue by natman** [myoung34/vagrant-ovirt4#94]
It is not currently possible to add more than one private network, while native providers allow it. If I want more than one network, I must add any nic additional nic to the used template, but this is not vagrant covinient.

**Comment by cliffe** [comment]
Just adding that this is also something we have come up against. It would be good if vagrant-ovirt4 had support for defining multiple networks. As it is, subsequent networks seem to overwrite the first networks' settings.
