### ISSUE TITLE
JSON::ParserError `parse': 751: unexpected token at '' 

### ISSUE THREAD

**Issue by pasa-edoardo** [myoung34/vagrant-ovirt4#98]
### Vagrant version
2.1.2

### Vagrant-ovirt4 version
1.2.2

### Host operating system
CentOS Linux release 7.5

### Guest operating system
CentOS/dummy.box

### Vagrantfile

```
    Vagrant.configure("2") do |config|
    config.vm.box = 'ovirt4'
    config.vm.box_url = 'https://github.com/myoung34/vagrant-ovirt4/blob/master/example_box/dummy.box?raw=true'

    config.vm.provider :ovirt4 do |ovirt|
    ovirt.url = 'https://server/ovirt-engine/api'
    ovirt.username = "admin@internal"
    ovirt.password = "password"
    ovirt.insecure = true
    ovirt.debug = true
    end
    end
```

### Debug output
https://gist.github.com/pasa-edoardo/c79ec8f3f7e495bcd9fbab45126a97e9

### Expected behavior
It should create vm on ovirt

### Actual behavior
Apparently pass the authentication but crash when try to parse the configuration for create the vm.

### Steps to reproduce
1.     I have done an installation from scratch of vagrant and vagrant-ovirt 4.
2.     Edited Vagrantfile after "vagrant init"
3.     vagrant up --debug

**Comment by myoung34** [comment]
Can you try running against vagrant <2?
Last version I have verified against was `1.9.2`

**Comment by pasa-edoardo** [comment]
Hi, i'd try with vagrant  `1.9.2` , the same vagrantfile and the vagrant-ovirt4 (`1.2.2`). I have a comparable error with JSON Parser, this is the output:
https://gist.github.com/pasa-edoardo/4ddbf8700e32f957211d5c6fa5eb6411

I've also tried with the version `1.9.1` but the error is similar: 
https://gist.github.com/pasa-edoardo/4fdcf58d735eefe69cf14ca4edb70081

**Comment by myoung34** [comment]
Youre missing multiple required values, such as console,cluster and template.

Per readme: 

```
   1. `template` => The name of the template to use for creation. Required. String. No Default value.
   1. `cluster` => The name of the ovirt cluster to create within. Required. String. No Default value.
   1. `console` => The type of remote viewing protocol to use. Required. String. No Default value.
```

**Comment by pasa-edoardo** [comment]
I had try adding `template`,`cluster`,`console` but i have obtain the same error; i'm using this vagrant file:
```
Vagrant.configure("2") do |config|
  config.vm.box = 'ovirt4'
  config.vm.provider :ovirt4 do |ovirt|
    ovirt.url = 'http://ovengine.home.com/ovirt-engie/api'
    ovirt.username = "admin@internal"
    ovirt.password = "/tY\Hm;w[B2E3+kV"
    ovirt.cluster = 'Default'
    ovirt.template = 'vagrant-centos7'
    ovirt.console = 'novnc'
    ovirt.insecure = true
    ovirt.debug = true
  end
end
```
in the README, tagged like **Required** , there is **datacenter**  option but running `vagrant up` gave me this error:
> VagrantPlugins::OVirtProvider::Config:
> * The following settings shouldn't exist: datacenter
Vagrantfile is the same upon but with more `ovirt.datacenter = 'Default'` in *provider* section
i'd the same results with vagrant-ovirt4-1.2.1.

**Comment by myoung34** [comment]
Updated documentation, i dont think i completed `datacenter`

Can you post debug logs of error/etc after adding template/console/cluster?

**Comment by pasa-edoardo** [comment]
Sorry for not doing it before,
https://gist.github.com/pasa-edoardo/a040005758edba3ddad53afcbfb3c2f2
